### ISSUE TITLE
Cannot find module 'autoprefixer'

### ISSUE THREAD

**Issue by kjetilge** [scaphold-io/slackr-graphql-subscriptions-starter-kit#1]
When I try to run the app after npm install I get:
```
  [881] ./~/subscriptions-transport-ws/dist/server.js 6.93 kB {0} [built]
       [0] 2ms -> [265] 5798ms -> [839] 1604ms -> [871] 2473ms -> factory:1580ms building:318ms dependencies:735ms = 12510ms

ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/sass-loader!./src/components/index.scss
Module build failed: Error: Cannot find module 'autoprefixer'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kjetilge/Documents/Dev/Apollo/slackr-graphql-subscriptions-starter-kit/postcss.config.js:14:3)
    at Module._compile (module.js:409:26)
    at requireFromString (/Users/kjetilge/Documents/Dev/Apollo/slackr-graphql-subscriptions-starter-kit/node_modules/postcss-loader/node_modules/postcss-load-config/node_modules/cosmiconfig/node_modules/require-from-string/index.js:27:4)
    at /Users/kjetilge/Documents/Dev/Apollo/slackr-graphql-subscriptions-starter-kit/node_modules/postcss-loader/node_modules/postcss-load-config/node_modules/cosmiconfig/lib/loadJs.js:11:15
 @ ./src/components/index.scss 4:14-243 13:2-17:4 14:20-249

ERROR in ./~/auth0-lock/~/react/lib/ReactAddonsDOMDependencies.js
Module not found: Error: Cannot resolve module 'react-dom/lib/ReactDOM' in /Users/kjetilge/Documents/Dev/Apollo/slackr-graphql-subscriptions-starter-kit/node_modules/auth0-lock/node_modules/react/lib
 @ ./~/auth0-lock/~/react/lib/ReactAddonsDOMDependencies.js 13:15-48

ERROR in ./~/auth0-lock/~/react/lib/ReactAddonsDOMDependencies.js
Module not found: Error: Cannot resolve module 'react-dom/lib/ReactPerf' in /Users/kjetilge/Documents/Dev/Apollo/slackr-graphql-subscriptions-starter-kit/node_modules/auth0-lock/node_modules/react/lib
 @ ./~/auth0-lock/~/react/lib/ReactAddonsDOMDependencies.js 25:18-52

ERROR in ./~/auth0-lock/~/react/lib/ReactAddonsDOMDependencies.js
Module not found: Error: Cannot resolve module 'react-dom/lib/ReactTestUtils' in /Users/kjetilge/Documents/Dev/Apollo/slackr-graphql-subscriptions-starter-kit/node_modules/auth0-lock/node_modules/react/lib
 @ ./~/auth0-lock/~/react/lib/ReactAddonsDOMDependencies.js 32:23-62

ERROR in ./~/auth0-lock/~/react/lib/ReactTransitionEvents.js
Module not found: Error: Cannot resolve module 'react-dom/lib/getVendorPrefixedEventName' in /Users/kjetilge/Documents/Dev/Apollo/slackr-graphql-subscriptions-starter-kit/node_modules/auth0-lock/node_modules/react/lib
 @ ./~/auth0-lock/~/react/lib/ReactTransitionEvents.js 15:33-84
```

**Comment by kjetilge** [comment]
The problem went away when using latest node :-)

**Comment by vning93** [comment]
Awesome, great to hear!
